server.port=8080

openai.base-url=https://openrouter.ai/api/v1
openai.model-name=qwen/qwen3-235b-a22b-2507
openai.api-key=${API-KEY}
openai.temperature=0.2
openai.max-tokens=4096

# API key refresh TTL in seconds (10 minutes)
openai.api-key-ttl-seconds=600

agent.skills.classpath=skills