server.port=8080

openai.base-url=https://openrouter.ai/api/v1
openai.model-name=qwen/qwen3-coder-next
openai.api-key=${API-KEY}
openai.temperature=0.7
openai.max-tokens=1024

# API key refresh TTL in seconds (10 minutes)
openai.api-key-ttl-seconds=600

agent.skills.classpath=skills